#!/usr/bin/python3
import sys
import os
from src.test import test

if __name__ == "__main__":
    input_file = sys.argv[1]
    n_questions = sys.argv[2]
    print("answering...")
    
    os.chdir("src/ask/")

    test.main()